// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file dvae.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace win_test
{
    
    public sealed class dvaeInput
    {
        public ImageFeatureValue modelInput; // shape(1,5,128,128)
    }
    
    public sealed class dvaeOutput
    {
        public TensorDouble output; // shape(1,5,128,128)
        public TensorDouble onnx00Gemm_74; // shape(1,32)
        public TensorFloat mu; // shape(1,32)
        public TensorFloat logvar; // shape(1,32)
    }
    
    public sealed class dvaeModel
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<dvaeModel> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            dvaeModel learningModel = new dvaeModel();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<dvaeOutput> EvaluateAsync(dvaeInput input)
        {
            binding.Bind("input", input.modelInput);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new dvaeOutput();
            output.output = result.Outputs["output"] as TensorDouble;
            output.onnx00Gemm_74 = result.Outputs["onnx::Gemm_74"] as TensorDouble;
            output.mu = result.Outputs["mu"] as TensorFloat;
            output.logvar = result.Outputs["logvar"] as TensorFloat;
            return output;
        }
    }
}

